backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img

collections:
  - name: "home"
    label: "Home"
    folder: "src/content/home"
    create: true
    slug: "index"
    media_folder: ""
    public_folder: ""
    path: "{{title}}/index"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Path", name: "path", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - {
          label: "Category",
          name: "category",
          widget: "select",
          options: ["Home"],
        }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "css"
    label: "CSS"
    folder: "src/content/css"
    create: true
    slug: "index"
    media_folder: ""
    public_folder: ""
    path: "{{title}}/index"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Path", name: "path", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - {
          label: "Category",
          name: "category",
          widget: "select",
          options: ["CSS"],
        }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "design"
    label: "Design"
    folder: "src/content/design"
    create: true
    slug: "index"
    media_folder: ""
    public_folder: ""
    path: "{{title}}/index"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Path", name: "path", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - {
          label: "Category",
          name: "category",
          widget: "select",
          options: ["Design"],
        }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "javascript"
    label: "JavaScript"
    folder: "src/content/javascript"
    create: true
    slug: "index"
    media_folder: ""
    public_folder: ""
    path: "{{title}}/index"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Path", name: "path", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - {
          label: "Category",
          name: "category",
          widget: "select",
          options: ["JavaScript"],
        }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "tools"
    label: "Tools"
    folder: "src/content/tools"
    create: true
    slug: "index"
    media_folder: ""
    public_folder: ""
    path: "{{title}}/index"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Path", name: "path", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - {
          label: "Category",
          name: "category",
          widget: "select",
          options: ["Tools"],
        }
      - { label: "Body", name: "body", widget: "markdown" }
